feat: Adiciona nome jose valter no README
meliuz-training/welcome pull request #24
Opened 2021-11-09 20:02 UTC by Feriow

Confirmo que fiz as seguintes tarefas:

- [ ] Configurei o e-mail Méliuz (`nome.sobrenome@meliuz.com.br`) para uso com o Git no [GitHub](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github)
- [ ] Configurei o e-mail Méliuz (`nome.sobrenome@meliuz.com.br`) para uso com o Git no [terminal](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git)
- [ ] Configurei o nome do autor, usando o comando `git config --global user.name "Nome Sobrenome"`, substituindo com meus dados
- [ ] Adicionei meu nome e sobrenome ao arquivo README.md desse repositório (veja exemplo em https://github.com/meliuz-training/welcome)

2021-11-09 23:22 UTC, lizardo requested changes
@Feriow dois pontos:

- O author e o email da sua configuração de Git estão com os dados pessoais. Pode ajustar para usar "Nome Sobrenome" e o seu e-mail Méliuz?

- preciso que faça rebase para o `origin/main` mais recente, corrigindo o conflito que aparecer. Passo-a-passo aqui: https://mliuztechexpe-gyr7246.slack.com/archives/C02MCLMG5TJ/p1636483203032900

Dica para escolher uma boa mensagem de commit durante a resolução de conflito: https://mliuztechexpe-gyr7246.slack.com/archives/C02MCLMG5TJ/p1636482858030800

2021-11-10 20:27 UTC, Feriow commented
@lizardo,

Tentei fazer o que você pediu e espero que tenha funcionado. Depois me dá um feedback se falta algo mais.

2021-11-10 22:42 UTC, lizardo commented
@Feriow Olha como ficou graficamente seus commits:

![image](https://user-images.githubusercontent.com/383724/141204234-59bafd50-8c19-4a8e-8ddb-43fb784f9ce0.png)

Pontos para corrigir:

Durante o processo de resolver o conflito, você acabou fazendo commit dos marcadores (`<<<<< HEAD`, `==========`, `>>>>>>>> ...` ) que deveriam ser removidos **antes** de criar o commit.

Você acabou criando 2 commits por causa disso, um adicionando os marcadores, outro removendo.

Além disso, não deveria haver um commit de merge. Você precisa fazer um rebase como orientado aqui: https://mliuztechexpe-gyr7246.slack.com/archives/C02MCLMG5TJ/p1636482763028800?thread_ts=1636466051.006300&cid=C02MCLMG5TJ

Fazendo essas correções, deverá ficar apenas 1 commit, com a descrição `feat: Adiciona nome jose valter no README` (ou algo parecido)

Mais detalhes de como resolver conflitos no Git: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

Sugiro tentar resolver por um tempo por conta própria, mas se ainda não tiver conseguindo, pode me procurar que demonstro :wink: 

Você também pode revisar os primeiros 15 min da aula de ontem 9/nov (link [aqui](https://mliuztechexpe-gyr7246.slack.com/archives/C02JDCUCESK/p1636549364007200)) onde resolvo um conflito.

2021-11-10 23:24 UTC, Feriow commented
@lizardo , eu segui exatamente os comandos da thread do slack e acho que ainda acabei com 2 commits, se é que tou sabendo onde olhar isso.

2021-11-10 23:55 UTC, lizardo commented
@Feriow Exato, o motivo é que no seu histórico tem os marcadores de conflito que não deveriam ter sido mantidos no commit... Aí no primeiro commit vc adicionou os marcadores:

![image](https://user-images.githubusercontent.com/383724/141212024-49787880-7268-4e14-a8e7-46390075940b.png)

E no segundo commit, removeu eles:

![image](https://user-images.githubusercontent.com/383724/141212073-8649a320-18bf-4edd-ba05-84a5279a52fc.png)

Para resolver isso, você precisa "mesclar" os dois commit. Isso é chamado "squashing" no git:

https://medium.com/cwi-software/utilizando-rebase-e-squash-para-melhorar-o-hist%C3%B3rico-do-git-fdb2d952c09c

Mas você já faz a primeira parte do que falei: não tem mais "merge commit", falta apenas esse squashing para eliminar os marcadores de conflito do historico e ficar apenas um commit que adiciona a linha.

2021-11-11 00:36 UTC, Feriow commented
@lizardo Parece que consegui reduzir para um commit, mas não deu certo por squash. Eu fiz git reset --hard HEAD~1 duas vezes e depois segui as instruções daquela thread da Renata.

2021-11-13 13:40 UTC, lizardo approved these changes

2021-11-13 13:41 UTC, lizardo commented
@Feriow tudo bem! O resultado ficou como esperado agora. Vou mostrar pra turma como ocorreria este sqash, pois teve outro caso identico ao seu :smile:

2021-11-13 13:41 UTC, merged