Add Carolyne Lira Carvalho to README.md
meliuz-training/welcome pull request #5
Opened 2021-11-09 11:54 UTC by CarolLira

Confirmo que fiz as seguintes tarefas:

- [x] Configurei o e-mail Méliuz (`nome.sobrenome@meliuz.com.br`) para uso com o Git no [GitHub](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github)
- [x] Configurei o e-mail Méliuz (`nome.sobrenome@meliuz.com.br`) para uso com o Git no [terminal](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git)
- [x] Configurei o nome do autor, usando o comando `git config --global user.name "Nome Sobrenome"`, substituindo com meus dados
- [x] Adicionei meu nome e sobrenome ao arquivo README.md desse repositório (veja exemplo em https://github.com/meliuz-training/welcome)

2021-11-09 12:53 UTC, lizardo commented on README.md
> +- Carolyne Lira Carvalho
@CarolLira Poderia colocer em ordem alfabética (pelo primeiro nome)?

2021-11-09 15:09 UTC, lizardo requested changes
@CarolLira Poderia colocar em ordem alfabética (pelo primeiro nome)?

Ah, e fazer rebase, pois deverá dar conflito :-) 

Qualquer dúvida, me procura!

2021-11-09 20:41 UTC, lizardo commented
@CarolLira  como pode ver na imagem abaixo, você ainda tem um commit de merge (note os 2 parent):

![image](https://user-images.githubusercontent.com/383724/141001072-2019e2a1-dff8-4f87-a6d3-ff11ca028193.png)

Poderia seguir esses passos colocados no Slack e ver se consegue aplicar um rebase ?

https://mliuztechexpe-gyr7246.slack.com/archives/C02MCLMG5TJ/p1636482763028800?thread_ts=1636466051.006300&cid=C02MCLMG5TJ

2021-11-09 21:28 UTC, CarolLira commented
> @CarolLira como pode ver na imagem abaixo, você ainda tem um commit de merge (note os 2 parent):
> 
> ![image](https://user-images.githubusercontent.com/383724/141001072-2019e2a1-dff8-4f87-a6d3-ff11ca028193.png)
> 
> Poderia seguir esses passos colocados no Slack e ver se consegue aplicar um rebase ?
> 
> https://mliuztechexpe-gyr7246.slack.com/archives/C02MCLMG5TJ/p1636482763028800?thread_ts=1636466051.006300&cid=C02MCLMG5TJ

2021-11-09 21:29 UTC, CarolLira commented
deu certo?

2021-11-09 22:52 UTC, lizardo requested changes
@CarolLira acho que é mais simples criar um novo branch na sua máquina, fazer apenas a alteração no README.md e subir diretamente para o branch da PR:

1. `git fetch -p`
2. `git checkout -b tmp origin/main`
3. Editar o README.md e adicionar seu nome
4. `git add README.md`
5. `git commit -m 'Sua mensagem de commit'`
6. `git push -f origin tmp:feature/carolyneLiraCarvalho`
7. `git branch -D tmp` (apaga o branch localmente)

Mas pode ver no inicio da gravação da aula de hoje como fiz a correção direto no branch original (mas não subi, fiz apenas localmente)

2021-11-11 20:21 UTC, CarolLira commented
> @CarolLira acho que é mais simples criar um novo branch na sua máquina, fazer apenas a alteração no README.md e subir diretamente para o branch da PR:
> 
> 1. `git fetch -p`
> 2. `git checkout -b tmp origin/main`
> 3. Editar o README.md e adicionar seu nome
> 4. `git add README.md`
> 5. `git commit -m 'Sua mensagem de commit'`
> 6. `git push -f origin tmp:feature/carolyneLiraCarvalho`
> 7. `git branch -D tmp` (apaga o branch localmente)
> 
> Mas pode ver no inicio da gravação da aula de hoje como fiz a correção direto no branch original (mas não subi, fiz apenas localmente)

2021-11-13 14:22 UTC, lizardo approved these changes

2021-11-13 14:22 UTC, merged