adiciona Lucas Lopes ao README.md
meliuz-training/welcome pull request #6
Opened 2021-11-09 12:10 UTC by thebestlucc

Confirmo que fiz as seguintes tarefas:

- [x] Configurei o e-mail Méliuz (`nome.sobrenome@meliuz.com.br`) para uso com o Git no [GitHub](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github)
- [x] Configurei o e-mail Méliuz (`nome.sobrenome@meliuz.com.br`) para uso com o Git no [terminal](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git)
- [x] Configurei o nome do autor, usando o comando `git config --global user.name "Nome Sobrenome"`, substituindo com meus dados
- [x] Adicionei meu nome e sobrenome ao arquivo README.md desse repositório (veja exemplo em https://github.com/meliuz-training/welcome)

2021-11-09 12:57 UTC, lizardo requested changes

2021-11-09 12:57 UTC, lizardo commented on pull_request_template.md
> +- [x] Configurei o nome do autor, usando o comando `git config --global user.name "Nome Sobrenome"`, substituindo com meus dados
Seu nome ficou sem o espaço entre o nome e sobrenome:

```
LucasLopes
```

poderia corrigir?  basta repetir esse comando do `git config ...`  e então , estando no branch, executar:

```
git commit --amend --reset-author
```

e então fazer um push forçado para atualizar a PR:

```
git push -f
```

Avise aqui se tiver algum problema!

2021-11-09 20:05 UTC, thebestlucc commented on pull_request_template.md
> +- [x] Configurei o nome do autor, usando o comando `git config --global user.name "Nome Sobrenome"`, substituindo com meus dados
Prontinho, fiz isso daí

2021-11-09 22:42 UTC, lizardo requested changes
@thebestlucc  sua PR tem alterações no arquivo `pull_request_template.md` que devem ser removidas, pois esse arquivo é um template que não deve ser modificado.

Poderia corrigir? (ou seja, remover o arquivo da PR, deixando apenas a alteração no README.md)

2021-11-10 00:01 UTC, lizardo commented on pull_request_template.md
> +- [x] Configurei o nome do autor, usando o comando `git config --global user.name "Nome Sobrenome"`, substituindo com meus dados
@thebestlucc seu nome continua incorrento, revja se vc rodou o `git config --global user.name "Lucas Lopes"`  e rode `git config --global user.name`   para confirmar que o nome foi corrigido (adicionado o espaço).

E entao repita:

```
git commit --amend --reset-author
git push -f origin feature/lucas-lopes
```

Pode aproveitar e dar um rebase para o `origin/main` mais recente também?

2021-11-10 19:33 UTC, thebestlucc commented on pull_request_template.md
> +- [x] Configurei o nome do autor, usando o comando `git config --global user.name "Nome Sobrenome"`, substituindo com meus dados
@lizardo vê se agora foi certo, descobri o que rolou, acredito que acacbei rodando o comando _git config user.name LucasLopes_ e depois rodei o nome certo com a flag _--global_ por isso acabou indo com o nome errado (no arquivo de config ficou salvo dois itens _user.name_

2021-11-10 22:16 UTC, lizardo approved these changes
@thebestlucc Tudo certo!

2021-11-10 22:16 UTC, merged